using System.Text;
using Microsoft.CodeAnalysis;
using SQLSharp.Generator.Result;
using SQLSharp.Generator.Types;

namespace SQLSharp.Generator;

public static class SourceGenerationHelper
{
    private static readonly DiagnosticDescriptor TypeIsNotPartial =
        new(
            "SQLSHARP001",
            "Annotated type is not partial",
            "'{0}' must be partial to allow for adding extra behaviour",
            "SQLSharp Generation",
            DiagnosticSeverity.Error,
            true);
    private static readonly DiagnosticDescriptor TypeInvalidWrapperType =
        new(
            "SQLSHARP002",
            "Annotated type is not a valid wrapper type",
            "'{0}' must have exactly 1 field or property to be a wrapper type",
            "SQLSharp Generation",
            DiagnosticSeverity.Error,
            true);

    public const string RenameEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace SQLSharp.Generator.Result;

        public enum Rename
        {
            SnakeCase,
            CamelCase,
            PascalCase,
            UpperCase,
            LowerCase,
            None,
        }
        """;

    public const string FromRowAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace SQLSharp.Generator.Result;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
        public sealed class FromRowAttribute : global::System.Attribute
        {
            public Rename RenameAll { get; set; } = Rename.None;
        }
        """;

    public const string ColumnAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace SQLSharp.Generator.Result;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property)]
        public sealed class ColumnAttribute : global::System.Attribute
        {
            public string Rename { get; set; } = string.Empty;
            public bool Flatten { get; set; } = false;
        }
        """;

    public static string GenerateRowParserPartialClass(
        RowParserToGenerate rowParserToGenerate,
        SourceProductionContext sourceProductionContext)
    {
        if (!rowParserToGenerate.IsPartial)
        {
            sourceProductionContext.ReportDiagnostic(
                Diagnostic.Create(TypeIsNotPartial, Location.None,
                    rowParserToGenerate.Name));
            return string.Empty;
        }

        ConstructorData? constructor;
        if (rowParserToGenerate.IsStruct)
        {
            constructor = rowParserToGenerate.Constructors
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();
        }
        else
        {
            constructor = rowParserToGenerate.Constructors
                .OrderBy(c => c.Parameters.Length)
                .FirstOrDefault();
        }

        var instanceBuilder = constructor is null
            ? BuildInitializer(rowParserToGenerate)
            : BuildConstructorCall(rowParserToGenerate, constructor);

        var type = rowParserToGenerate.IsStruct ? "struct" : "class";
        var typeNamespace = string.IsNullOrWhiteSpace(rowParserToGenerate.Namespace)
            ? string.Empty
            : $"{rowParserToGenerate.Namespace}.";
        return
            $$"""
              // <auto-generated/>
              #nullable enable

              partial {{type}} {{typeNamespace}}{{rowParserToGenerate.Name}} : SQLSharp.Result.IFromRow<{{rowParserToGenerate.Name}}>
              {
                  public static {{rowParserToGenerate.Name}} FromRow(SQLSharp.Result.IDataRow row)
                  {
                      return new {{rowParserToGenerate.Name}}{{instanceBuilder}};
                  }
              }
              """;
    }

    private static string BuildInitializer(RowParserToGenerate rowParserToGenerate)
    {
        InitializerData initializerData = rowParserToGenerate.InitializerData;
        var builder = new StringBuilder(initializerData.Properties.Length > 0
            ? "\n        {\n            "
            : "{");
        for (var index = 0; index < initializerData.Properties.Length; index++)
        {
            FieldData field = initializerData.Properties[index];

            var fieldName = field.HasRename
                ? field.ResultFieldName
                : rowParserToGenerate.Rename.TransformRowFieldName(field.ResultFieldName);

            builder.Append(field.Name);
            builder.Append(" = ");

            if (field.Flatten)
            {
                builder.AppendFullTypeName(field.TypeData);
                builder.Append(".FromRow(row)");
                continue;
            }

            if (field.TypeData.IsDecode)
            {
                builder.AppendFullTypeName(field.TypeData);
                builder.Append(".Decode(row, row.IndexOf(\"");
                builder.Append(fieldName);
                builder.Append("\"))");
                continue;
            }

            builder.Append("row.GetField");
            if (!field.TypeData.IsNullable)
            {
                builder.Append("NotNull");
            }

            builder.Append('<');
            builder.AppendFullTypeName(field.TypeData);
            if (field.TypeData is { IsRefType: false, IsNullable: true })
            {
                builder.Append('?');
            }

            builder.Append('>');
            builder.Append("(\"");
            builder.Append(fieldName);
            builder.AppendLine("\"),");

            if (index >= initializerData.Properties.Length - 1) continue;

            builder.Append("            ");
        }

        builder.Append("        }");
        return builder.ToString();
    }

    private static string BuildConstructorCall(
        RowParserToGenerate rowParserToGenerate,
        ConstructorData constructor)
    {
        var builder = new StringBuilder(constructor.Parameters.Length > 0
            ? "(\n            "
            : "(");
        for (var index = 0; index < constructor.Parameters.Length; index++)
        {
            FieldData field = constructor.Parameters[index];

            var fieldName = field.HasRename
                ? field.ResultFieldName
                : rowParserToGenerate.Rename.TransformRowFieldName(field.ResultFieldName);

            builder.Append(field.Name);
            builder.Append(": ");

            if (field.Flatten)
            {
                builder.AppendFullTypeName(field.TypeData);
                builder.Append(".FromRow(row)");
                continue;
            }

            if (field.TypeData.IsDecode)
            {
                builder.AppendFullTypeName(field.TypeData);
                builder.Append(".Decode(row, row.IndexOf(\"");
                builder.Append(fieldName);
                builder.Append("\"))");
                continue;
            }

            builder.Append("row.GetField");
            if (!field.TypeData.IsNullable)
            {
                builder.Append("NotNull");
            }

            builder.Append('<');
            builder.AppendFullTypeName(field.TypeData);
            if (field.TypeData is { IsRefType: false, IsNullable: true })
            {
                builder.Append('?');
            }

            builder.Append('>');
            builder.Append("(\"");
            builder.Append(fieldName);
            builder.Append("\")");

            if (index >= constructor.Parameters.Length - 1) continue;

            builder.Append(',');
            builder.AppendLine();
            builder.Append("            ");
        }

        builder.Append(')');
        return builder.ToString();
    }

    private static void AppendFullTypeName(
        this StringBuilder builder,
        FieldTypeData typeData)
    {
        if (!string.IsNullOrEmpty(typeData.ContainingNamespace))
        {
            builder.Append(typeData.ContainingNamespace);
            builder.Append('.');
        }

        builder.Append(typeData.Name);
    }

    public static string GetFullNamespaceName(this INamespaceSymbol namespaceSymbol)
    {
        if (string.IsNullOrEmpty(namespaceSymbol.Name))
        {
            return string.Empty;
        }

        StringBuilder builder = new(namespaceSymbol.Name);
        INamespaceSymbol currentNamespace = namespaceSymbol.ContainingNamespace;
        while (!string.IsNullOrEmpty(currentNamespace.Name))
        {
            builder.Insert(0, '.');
            builder.Insert(0, currentNamespace.Name);
            currentNamespace = currentNamespace.ContainingNamespace;
        }

        return builder.ToString();
    }

    public const string WrapperTypeAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace SQLSharp.Generator.Types;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
        public sealed class WrapperTypeAttribute : global::System.Attribute
        {
        }
        """;

    public static string GenerateWrapperDecode(
        WrapperTypeToGenerate wrapperTypeToGenerate,
        SourceProductionContext sourceProductionContext)
    {
        if (!wrapperTypeToGenerate.IsPartial)
        {
            sourceProductionContext.ReportDiagnostic(
                Diagnostic.Create(
                    TypeIsNotPartial,
                    Location.None,
                    wrapperTypeToGenerate.Name));
            return string.Empty;
        }

        if (wrapperTypeToGenerate.InnerValue is null)
        {
            sourceProductionContext.ReportDiagnostic(
                Diagnostic.Create(
                    TypeInvalidWrapperType,
                    Location.None,
                    wrapperTypeToGenerate.Name));
            return string.Empty;
        }
        
        var type = wrapperTypeToGenerate.IsStruct ? "struct" : "class";
        var typeNamespace = string.IsNullOrWhiteSpace(wrapperTypeToGenerate.Namespace)
            ? string.Empty
            : $"{wrapperTypeToGenerate.Namespace}.";
        var innerValueDbType = GetDbType(wrapperTypeToGenerate.InnerValue.TypeName);
        var parameterTypeAssignment = innerValueDbType is null
            ? string.Empty
            : $"parameter.DbType = System.Data.DbType.{innerValueDbType};\n        ";
        var initialization = wrapperTypeToGenerate.HasNonDefaultConstructor
            ? $"return new {wrapperTypeToGenerate.Name}(row.GetField<{wrapperTypeToGenerate.InnerValue.TypeName}>(column));"
            : $$"""
                return new {{wrapperTypeToGenerate.Name}}
                        {
                            {{wrapperTypeToGenerate.InnerValue.Name}} = row.GetField<{{wrapperTypeToGenerate.InnerValue.TypeName}}>(column)
                        };
                """;
        return
            $$"""
              // <auto-generated/>
              #nullable enable

              partial {{type}} {{typeNamespace}}{{wrapperTypeToGenerate.Name}} : SQLSharp.Types.IDbDecode<{{typeNamespace}}{{wrapperTypeToGenerate.Name}}>, SQLSharp.Types.IDbEncode
              {
                  public void Encode(ref System.Data.IDbDataParameter parameter)
                  {
                      {{parameterTypeAssignment}}parameter.Value = {{wrapperTypeToGenerate.InnerValue.Name}};
                  }
              
                  public static {{typeNamespace}}{{wrapperTypeToGenerate.Name}} Decode(SQLSharp.Result.IDataRow row, int column)
                  {
                      {{initialization}}
                  }
              }
              """;
    }

    public static string? GetDbType(string parameter)
    {
        return parameter switch
        {
            "System.Boolean" => "Boolean",
            "System.Byte" => "SByte",
            "System.Int16" => "Int16",
            "System.UInt16" => "UInt16",
            "System.Int32" => "Int32",
            "System.UInt32" => "UInt32",
            "System.Int64" => "Int64",
            "System.UInt64" => "UInt64",
            "System.Byte[]" => "Binary",
            "System.Char" => "String",
            "System.Char[]" => "String",
            "System.String" => "String",
            "System.Decimal" => "Decimal",
            "System.Single" => "Single",
            "System.Double" => "Double",
            "System.DateTime" => "DateTime",
            "System.DateTimeOffset" => "DateTimeOffset",
            "System.Guid" => "Guid",
            _ => null,
        };
    }
}
