//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial class GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow
        {
            Id = row.GetFieldNotNull<System.Guid>("ID"),
            Name = row.GetFieldNotNull<System.String>("NAME"),
            Age = row.GetFieldNotNull<System.Byte>("AGE"),
            DateOfBirth = row.GetField<System.DateTime?>("DATEOFBIRTH"),
        };
    }
}