//HintName: ColumnAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace SQLSharp.Generator.Result;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, AllowMultiple = true)]
sealed class ColumnAttribute : global::System.Attribute
{
    public string? Name { get; set; } = null;
}