//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

using SQLSharp.Result;
using System;

partial struct GeneratedRow : IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(IDataRow row)
    {
        return new GeneratedRow(
            row.GetFieldNotNull<Guid>("id"),
            row.GetFieldAsClassNotNull<String>("name"),
            row.GetFieldNotNull<Byte>("age"),
            row.GetField<DateTime>("dateOfBirth"));
    }
}