//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial struct GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow(
            id: row.GetFieldNotNull<Guid>("ID"),
            name: row.GetFieldNotNull<System.String>("NAME"),
            age: row.GetFieldNotNull<System.Byte>("AGE"),
            dateOfBirth: row.GetField<System.DateTime?>("DATEOFBIRTH"));
    }
}