//HintName: FromRowAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace SQLSharp.Generator.Result;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = true)]
sealed class FromRowAttribute : global::System.Attribute
{
}