//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial class GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow
        {
            id = row.GetFieldNotNull<System.Guid>("Id"),
            name = row.GetFieldNotNull<System.String>("Name"),
            age = row.GetFieldNotNull<System.Byte>("Age"),
            dateOfBirth = row.GetField<System.DateTime?>("DateOfBirth"),
        };
    }
}