//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial class GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow
        {
            Id = row.GetFieldNotNull<System.Guid>("id"),
            Name = row.GetFieldNotNull<System.String>("name"),
            Age = row.GetFieldNotNull<System.Byte>("age"),
            DateOfBirth = row.GetField<System.DateTime?>("DateOfBirth"),
        };
    }
}