//HintName: Rename.g.cs
// <auto-generated/>
#nullable enable

namespace SQLSharp.Generator.Result;

public enum Rename
{
    SnakeCase,
    CamelCase,
    PascalCase,
    UpperCase,
    LowerCase,
    None,
}