//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

using SQLSharp.Result;
using System;

partial struct GeneratedRow : IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(IDataRow row)
    {
        return new GeneratedRow(
            id: row.GetFieldNotNull<Guid>("id"),
            name: row.GetFieldNotNull<String>("name"),
            age: row.GetFieldNotNull<Byte>("age"),
            dateOfBirth: row.GetField<DateTime?>("dateofbirth"));
    }
}