//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial class GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow(
            original: row.GetFieldNotNull<GeneratedRow>("original"));
    }
}