//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial class GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow
        {
            id = row.GetFieldNotNull<System.Guid>("id"),
            NaMe = row.GetFieldNotNull<System.String>("NaMe"),
            aGe = row.GetFieldNotNull<System.Byte>("aGe"),
            daTeOFBiRth = row.GetField<System.DateTime?>("daTeOFBiRth"),
        };
    }
}