//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

using SQLSharp.Result;
using System;

partial struct GeneratedRow : IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(IDataRow row)
    {
        return new GeneratedRow(
            id: row.GetFieldNotNull<Guid>("id"),
            NaMe: row.GetFieldNotNull<String>("NaMe"),
            aGe: row.GetFieldNotNull<Byte>("aGe"),
            daTeOFBiRth: row.GetField<DateTime?>("daTeOFBiRth"));
    }
}