//HintName: RowParsers.GeneratedRow.g.cs
// <auto-generated/>
#nullable enable

partial struct GeneratedRow : SQLSharp.Result.IFromRow<GeneratedRow>
{
    public static GeneratedRow FromRow(SQLSharp.Result.IDataRow row)
    {
        return new GeneratedRow(
            id: row.GetFieldNotNull<Guid>("id"),
            name: row.GetFieldNotNull<System.String>("name"),
            age: row.GetFieldNotNull<System.Byte>("age"),
            dateOfBirth: row.GetField<System.DateTime?>("dateofbirth"));
    }
}