//HintName: WrapperTypes.IntWrapper.g.cs
// <auto-generated/>
#nullable enable

using SQLSharp.Result;

partial struct IntWrapper : SQLSharp.Types.IDbDecode<IntWrapper>, SQLSharp.Types.IDbEncode
{
    public void Encode(ref System.Data.IDbDataParameter parameter)
    {
        parameter.DbType = System.Data.DbType.Int32;
        parameter.Value = Inner;
    }

    public static IntWrapper Decode(SQLSharp.Result.IDataRow row, int column)
    {
        return new IntWrapper
        {
            Inner = row.GetFieldNotNull<System.Int32>(column)
        };
    }
}