//HintName: WrapperTypeAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace SQLSharp.Generator.Types;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
public sealed class WrapperTypeAttribute : global::System.Attribute
{
}