//HintName: WrapperTypes.BytesWrapper.g.cs
// <auto-generated/>
#nullable enable

using SQLSharp.Result;

partial struct BytesWrapper : SQLSharp.Types.IDbDecode<BytesWrapper>, SQLSharp.Types.IDbEncode
{
    public void Encode(ref System.Data.IDbDataParameter parameter)
    {
        parameter.DbType = System.Data.DbType.Binary;
        parameter.Value = Inner;
    }

    public static BytesWrapper Decode(SQLSharp.Result.IDataRow row, int column)
    {
        return new BytesWrapper
        {
            Inner = row.GetFieldNotNull<System.Byte[]>(column)
        };
    }
}